- name: install and run nginx
  hosts: web
  become: yes # -b 
  tasks: 
   - name: install nginx
     ansible.builtin.package:
       name: nginx
       state: present #install absent=remove
   - name: start nginx
     ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes